# This R script can be used in conjunction with a PostgreSQL spatially-enabled databased to create a
# polygon around a given set of points using the pgRouting pgr_pointsAsPolygon function.
# This is useful for visualising the catchment area around sites or facilities.

# Load required libraries
library(RPostgreSQL)

# define the database connection - amend as required
drv <- dbDriver("PostgreSQL")
con <-
  dbConnect(
    drv, host = "localhost", user = "postgres", password = "password", dbname =
      "spatial"
  )

# create a table called catchment_polygons which will store the site catchment polygons
query <-
  paste(
    "CREATE TABLE public.catchment_polygons(gid serial NOT NULL PRIMARY KEY, name text)", sep =
      ""
  )
dbGetQuery(con, query)

# add geometry column with CRS 27700 - amend CRS as required
query <-
  paste(
    "SELECT AddGeometryColumn('public','catchment_polygons','geom', 27700, 'polygon', 2)", sep =
      ""
  )
dbGetQuery(con, query)


# get list of distinct sites from the survey table
query1 <-
  paste("SELECT DISTINCT site FROM public.survey", sep = "")
sites <- dbGetQuery(con, query1)

# loop through the sites dataframe and for each site create a temporary table holding observations relating to that site
# then update the catchment_polygons table with the polygon generated by pgr_pointsASPolygon

for (i in 1:nrow(sites)) {
  # create the temp table
  query2 <-
    paste(
      "CREATE TEMP TABLE catchment AS
      SELECT id, geom
      FROM public.survey
      where site = '", sites[i,1],"'", sep = ""
    )
  # this next line just removes line breaks from the query - allows the query to be written over mutiple lines as above
  query2 <- gsub(pattern = '\\s', replacement = " ", x = query2)
  dbGetQuery(con, query2)
  # pgr_pointsASPolygon requires at least 3 points, so do a row count of the catchment table
  count_rows <- dbGetQuery(con, "select count(*) from catchment")
  if (count_rows > 2) {
    # generate the polygon and insert into catchment_polygons table
    query3 <-
      paste(
        "INSERT INTO public.catchment_polygons (geom, name)
        VALUES (
        (ST_SetSRID(pgr_pointsASPolygon('SELECT id::integer AS id, st_x(geom)::float as x, st_y(geom)::float as y FROM catchment'),27700)),
        ('", sites[i,1], "'))", sep = ""
      )
    query3 <- gsub(pattern = '\\s', replacement = " ", x = query3)
    dbGetQuery(con, query3)
  }
  # drop the temp table
  dbGetQuery(con, "DROP TABLE catchment")
}
